Repository andruizgom/e-Geek-Collectibles, pull requests merged in 2023-12, with the labels that each got.

#41 update design in landing, detail and create shoping cart
  client/package-lock.json
  client/package.json
  client/prettier.config.cjs
  client/prettier.config.js
  client/src/App.css
  client/src/App.jsx
  client/src/assets/logo.svg
  client/src/components/Banner/Banner.jsx
  client/src/components/CartItem/CartItem.jsx
  client/src/components/CartSummary/CartSummary.jsx
  client/src/components/Categories/Categories.jsx
  client/src/components/Footer/Footer.jsx
  client/src/components/Navigation/Navigation.jsx
  client/src/components/ShoppingCar/Car.jsx
  client/src/components/Welcome/Welcome.jsx
  client/src/context/CartContext.jsx
  client/src/main.jsx
  client/src/views/Detail/Detail.jsx
  client/src/views/Detail/detail.css
  client/src/views/ShoppingCart/ShoppingCart.jsx
  client/tailwind.config.js
  client/vite.config.js
Labels: enhancement

#42 detail with favbutton
  client/src/components/FavButton/FavButton.jsx
  client/src/views/Detail/Detail.jsx
Labels: enhancement

#46 Leandro farnochi
  client/src/App.jsx
  client/src/views/ShippingForm/ShippingForm.jsx
Labels: enhancement

#47 Lucas dev
  client/package-lock.json
  client/package.json
  client/src/components/Stripe/PaymentForm.jsx
  client/src/views/Detail/Detail.jsx
  server/package-lock.json
  server/package.json
  server/src/controllers/Stripe/checkoutSession.js
  server/src/controllers/Stripe/infoProduct.js
  server/src/routes/index.js
Labels: enhancement

#51 design in filters componet
  client/src/components/Filters/Filters.jsx
  client/src/components/Filters/FiltersTest.jsx
  client/src/main.jsx
  client/src/views/Detail/Detail.jsx
  client/src/views/Home/Home.jsx
  client/tailwind.config.js
Labels: enhancement

#52 update design in home coponeent
  client/src/components/Card/Card.jsx
  client/src/components/Card/Card.styles.css
  client/src/components/Cards/Cards.jsx
  client/src/components/Cards/Cards.styles.css
  client/src/components/Filters/Filters.jsx
  client/src/components/Filters/FiltersTest.jsx
  client/src/views/Admin/Admin.styles.css
  client/src/views/Home/Home.jsx
  client/src/views/ShippingForm/ShippingForm.css
  client/src/views/UserForm/UserForm.styles.css
Labels: enhancement

#53 Brian dev
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/DropDown/AdDropDown.jsx
  client/src/components/Header/AdHeader.jsx
  client/src/components/Modals/Create.jsx
  client/src/components/Modals/Delete.jsx
  client/src/components/Modals/Read.jsx
  client/src/components/Modals/Update.jsx
  client/src/components/Modals/service/uploadImage.js
  client/src/components/Modals/service/useUploadImage.js
  client/src/components/Modals/service/validate.js
  client/src/components/Pagination/AdPagination.jsx
  client/src/components/SideBar/SideBar.jsx
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  client/src/views/Admin/Admin.jsx
  client/src/views/Orders/Orders.jsx
  client/src/views/Products/Products.jsx
  client/src/views/Users/Users.jsx
  client/tailwind.config.js
  client/vite.config.js.timestamp-1701448571381-cd94279c3341b.mjs
  server/src/controllers/updateProductC.js
  server/src/handlers/putUpdateProductH.js
  server/src/routes/index.js
Labels: enhancement

#54 Teo dev
  client/src/components/Stripe/PaymentForm.jsx
  client/src/main.jsx
  client/src/views/Detail/Detail.jsx
  server/src/controllers/Stripe/checkoutSession.js
Labels: enhancement

#55 Anderson dev
  client/src/App.jsx
  client/src/components/FavButton/FavButton.jsx
  client/src/components/Loging/Login.jsx
  client/src/components/Logout/Logout.jsx
  client/src/components/Navigation/Navigation.jsx
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  client/src/views/Landing/Landing.jsx
  client/src/views/UserForm/UserForm.jsx
Labels: bug, enhancement

#57 Lucas dev
  client/src/components/Stripe/PaymentForm.jsx
  client/src/views/Detail/Detail.jsx
  server/src/controllers/Stripe/checkoutSession.js
Labels: enhancement

#56 Backend_Checkout
  client/src/components/Logout/Logout.jsx
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  client/src/views/ShippingForm/ShippingForm.jsx
  server/index.js
  server/src/controllers/getShippingC.js
  server/src/controllers/postUserC.js
  server/src/controllers/updateShippingC.js
  server/src/handlers/getShippingH.js
  server/src/handlers/updateShippingH.js
  server/src/models/Users.js
  server/src/routes/index.js
Labels: enhancement

#58 Compras desde carrito y detail funcionando
  client/src/components/CartSummary/CartSummary.jsx
  client/src/components/Stripe/PaymentForm.jsx
  client/src/redux/types/index.js
  client/src/views/Detail/Detail.jsx
  client/src/views/ShoppingCart/ShoppingCart.jsx
  server/src/controllers/Stripe/checkoutSession.js
  server/src/controllers/Stripe/infoProduct.js
Labels: enhancement

#59 Create orders
  client/src/App.jsx
  client/src/components/CartSummary/CartSummary.jsx
  client/src/components/Favorites/Favorites.jsx
  client/src/redux/types/index.js
  client/src/views/Admin/Admin.jsx
  client/src/views/OrdersAdmin/OrdersAdmin.jsx
  client/src/views/OrdersUser/OrdersUser.jsx
  client/src/views/ShoppingCart/ShoppingCart.jsx
  client/src/views/User/User.jsx
  client/src/views/UserForm/UserForm.jsx
  client/src/views/failedPayment/failedPayment.jsx
  client/src/views/successfulPayment/successfullPayment.jsx
  server/src/controllers/Stripe/checkoutSession.js
  server/src/controllers/createOrderC.js
  server/src/controllers/getAllOrdersC.js
  server/src/controllers/getAllUsersC.js
  server/src/controllers/updateOrderC.js
  server/src/handlers/createOrderH.js
  server/src/handlers/getAllOrdersH.js
  server/src/handlers/updateOrderH.js
  server/src/models/Orders.js
  server/src/routes/index.js
Labels: enhancement

#61 Update main.jsx
  client/src/main.jsx
Labels: enhancement

#64 Lucas dev
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  server/src/models/Products.js
Labels: bug

#65 Dev
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  server/src/models/Products.js
Labels: enhancement

#49 Feature reviews
  client/src/App.jsx
  client/src/components/Review/OrderEvaluation.jsx
  client/src/components/Review/Review.jsx
  client/src/components/Review/Review.module.css
  client/src/components/Review/ReviewForm.jsx
  client/src/components/Review/ShowReview.jsx
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  client/src/views/Detail/Detail.jsx
  client/src/views/Detail/detail.css
  client/src/views/OrdersUser/OrdersUser.jsx
  client/src/views/User/User.jsx
  server/index.js
  server/src/controllers/createOrderC.js
  server/src/controllers/getAllReviewC.js
  server/src/controllers/postReviewC.js
  server/src/db.js
  server/src/handlers/getReviewH.js
  server/src/handlers/postReviewH.js
  server/src/models/Review.js
  server/src/routes/index.js
Labels: enhancement

#66 update design... fix some bugs
  client/src/App.jsx
  client/src/components/CartSummary/CartSummary.jsx
  client/src/components/FavButton/FavButton.jsx
  client/src/components/Filters/Filters.jsx
  client/src/components/Review/Review.jsx
  client/src/components/Review/Review.module.css
  client/src/components/Review/ShowReview.jsx
  client/src/components/SearchBar/SearchBar.jsx
  client/src/components/SearchBar/SearchBar.module.css
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/views/Detail/Detail.jsx
  client/src/views/Detail/detail.css
  client/src/views/Home/Home.jsx
  client/src/views/NotFound/NotFound.jsx
  client/src/views/ShoppingCart/ShoppingCart.jsx
Labels: enhancement

#68 Lean dev mails
  client/package-lock.json
  client/src/App.jsx
  client/src/assets/logo.png
  client/src/components/Logout/Logout.jsx
  client/src/components/SideBar/SideBar.jsx
  client/src/components/Stripe/PaymentForm.jsx
  client/src/main.jsx
  client/src/views/Detail/Detail.jsx
  client/src/views/Home/Home.jsx
  client/src/views/OrdersAdmin/OrdersAdmin.jsx
  client/src/views/OrdersUser/OrdersUser.jsx
  client/src/views/failedPayment/failedPayment.jsx
  client/src/views/successfulPayment/successfullPayment.jsx
  server/package-lock.json
  server/package.json
  server/src/controllers/createOrderC.js
  server/src/controllers/getAllOrdersC.js
  server/src/controllers/postUserC.js
  server/src/controllers/updateOrderC.js
  server/src/controllers/updateProductC.js
  server/src/email/mailConfig.js
  server/src/models/Products.js
  server/src/routes/index.js
Labels: enhancement

#69 Lucas dev
  client/src/components/Loging/Login.jsx
  client/src/components/Stripe/PaymentForm.jsx
  client/src/main.jsx
  client/src/views/Detail/Detail.jsx
  client/src/views/ShoppingCart/ShoppingCart.jsx
  client/src/views/User/User.jsx
  server/src/controllers/Stripe/checkoutSession.js
  server/src/controllers/getAllProductsC.js
Labels: enhancement

#73 Lucas dev
  server/src/server.js
Labels: bug

#74 Dev
  server/src/server.js
Labels: bug

#75 Lucas dev
  server/src/controllers/getAllProductsC.js
Labels: bug

#77 Lucas dev
  client/src/main.jsx
Labels: bug

#79 Lucas dev
  client/src/main.jsx
Labels: bug

#80 Dev
  client/src/main.jsx
Labels: bug

#87 Leandro farnochi
  client/src/components/NavBar/NavBar.jsx
  client/src/context/CartContext.jsx
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  client/src/views/Detail/Detail.jsx
  client/src/views/ShoppingCart/ShoppingCart.jsx
  server/src/controllers/deleteCartC.js
  server/src/controllers/getCartC.js
  server/src/controllers/postCartC.js
  server/src/controllers/updateQuantityC.js
  server/src/controllers/updateUserC.js
  server/src/db.js
  server/src/handlers/deleteCartH.js
  server/src/handlers/getCartH.js
  server/src/handlers/postCartH.js
  server/src/handlers/updateQuantityH.js
  server/src/models/Cart.js
  server/src/models/Users.js
  server/src/routes/index.js
Labels: enhancement

#88 Dev
  client/src/components/NavBar/NavBar.jsx
  client/src/context/CartContext.jsx
  client/src/redux/actions/index.js
  client/src/redux/reducer/index.js
  client/src/redux/types/index.js
  client/src/views/Detail/Detail.jsx
  client/src/views/ShoppingCart/ShoppingCart.jsx
  server/src/controllers/deleteCartC.js
  server/src/controllers/getCartC.js
  server/src/controllers/postCartC.js
  server/src/controllers/updateQuantityC.js
  server/src/controllers/updateUserC.js
  server/src/db.js
  server/src/handlers/deleteCartH.js
  server/src/handlers/getCartH.js
  server/src/handlers/postCartH.js
  server/src/handlers/updateQuantityH.js
  server/src/models/Cart.js
  server/src/models/Users.js
  server/src/routes/index.js
Labels: enhancement
